# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gangr_rpc.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import service as _service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='gangr_rpc.proto',
  package='gangr.rpc',
  serialized_pb='\n\x0fgangr_rpc.proto\x12\tgangr.rpc\"\x1a\n\x0b\x45\x63hoRequest\x12\x0b\n\x03str\x18\x01 \x02(\t\"\x1b\n\x0c\x45\x63hoResponse\x12\x0b\n\x03str\x18\x01 \x02(\t\"\x1f\n\rJobRpcRequest\x12\x0e\n\x06job_id\x18\x01 \x02(\x03\" \n\x0eJobRpcResponse\x12\x0e\n\x06status\x18\x01 \x02(\x08\x32\x8f\x02\n\x0cGangrService\x12\x37\n\x04\x65\x63ho\x12\x16.gangr.rpc.EchoRequest\x1a\x17.gangr.rpc.EchoResponse\x12@\n\tpause_job\x12\x18.gangr.rpc.JobRpcRequest\x1a\x19.gangr.rpc.JobRpcResponse\x12\x43\n\x0c\x63ontinue_job\x12\x18.gangr.rpc.JobRpcRequest\x1a\x19.gangr.rpc.JobRpcResponse\x12?\n\x08stop_job\x12\x18.gangr.rpc.JobRpcRequest\x1a\x19.gangr.rpc.JobRpcResponseB9\n\x1f\x63om.nosajia.rpc.example.protoB\x10\x45xampleRpcProtos\x88\x01\x01\x90\x01\x01')




_ECHOREQUEST = _descriptor.Descriptor(
  name='EchoRequest',
  full_name='gangr.rpc.EchoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='str', full_name='gangr.rpc.EchoRequest.str', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=30,
  serialized_end=56,
)


_ECHORESPONSE = _descriptor.Descriptor(
  name='EchoResponse',
  full_name='gangr.rpc.EchoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='str', full_name='gangr.rpc.EchoResponse.str', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=58,
  serialized_end=85,
)


_JOBRPCREQUEST = _descriptor.Descriptor(
  name='JobRpcRequest',
  full_name='gangr.rpc.JobRpcRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='job_id', full_name='gangr.rpc.JobRpcRequest.job_id', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=87,
  serialized_end=118,
)


_JOBRPCRESPONSE = _descriptor.Descriptor(
  name='JobRpcResponse',
  full_name='gangr.rpc.JobRpcResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='gangr.rpc.JobRpcResponse.status', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=120,
  serialized_end=152,
)

DESCRIPTOR.message_types_by_name['EchoRequest'] = _ECHOREQUEST
DESCRIPTOR.message_types_by_name['EchoResponse'] = _ECHORESPONSE
DESCRIPTOR.message_types_by_name['JobRpcRequest'] = _JOBRPCREQUEST
DESCRIPTOR.message_types_by_name['JobRpcResponse'] = _JOBRPCRESPONSE

class EchoRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ECHOREQUEST

  # @@protoc_insertion_point(class_scope:gangr.rpc.EchoRequest)

class EchoResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ECHORESPONSE

  # @@protoc_insertion_point(class_scope:gangr.rpc.EchoResponse)

class JobRpcRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _JOBRPCREQUEST

  # @@protoc_insertion_point(class_scope:gangr.rpc.JobRpcRequest)

class JobRpcResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _JOBRPCRESPONSE

  # @@protoc_insertion_point(class_scope:gangr.rpc.JobRpcResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\037com.nosajia.rpc.example.protoB\020ExampleRpcProtos\210\001\001\220\001\001')

_GANGRSERVICE = _descriptor.ServiceDescriptor(
  name='GangrService',
  full_name='gangr.rpc.GangrService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=155,
  serialized_end=426,
  methods=[
  _descriptor.MethodDescriptor(
    name='echo',
    full_name='gangr.rpc.GangrService.echo',
    index=0,
    containing_service=None,
    input_type=_ECHOREQUEST,
    output_type=_ECHORESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='pause_job',
    full_name='gangr.rpc.GangrService.pause_job',
    index=1,
    containing_service=None,
    input_type=_JOBRPCREQUEST,
    output_type=_JOBRPCRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='continue_job',
    full_name='gangr.rpc.GangrService.continue_job',
    index=2,
    containing_service=None,
    input_type=_JOBRPCREQUEST,
    output_type=_JOBRPCRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='stop_job',
    full_name='gangr.rpc.GangrService.stop_job',
    index=3,
    containing_service=None,
    input_type=_JOBRPCREQUEST,
    output_type=_JOBRPCRESPONSE,
    options=None,
  ),
])

class GangrService(_service.Service):
  __metaclass__ = service_reflection.GeneratedServiceType
  DESCRIPTOR = _GANGRSERVICE
class GangrService_Stub(GangrService):
  __metaclass__ = service_reflection.GeneratedServiceStubType
  DESCRIPTOR = _GANGRSERVICE

# @@protoc_insertion_point(module_scope)
